### ISSUE TITLE
Can't find the container in the GTM Library

### ISSUE THREAD

**Issue by GabrielOrmo** [stape-io/klaviyo-tag#1]
Hi Strape Io Team,
I've been trying to use your klaviyo container in GTM. However I can find it in the gallery, is it still available?

**Comment by Bukashk0zzz** [comment]
The tag is in the Community Template Gallery https://tagmanager.google.com/gallery/#/owners/stape-io/templates/klaviyo-tag
I think you try to add our tag to WEB GTM and not to the Server GTM container. 
And that's why you can't find it.
