### ISSUE TITLE
Email address written to stape_klaviyo_email

### ISSUE THREAD

**Issue by hanschr37** [stape-io/klaviyo-tag#14]
Hello, 

Emails are written to the stape_klaviyo_email cookie although I've left the "Store email in cookies" unticked. Is that normal behavior, and any tips on how it can be fixed? What I want is to prevent the emails from being written to the cookie

Looking forward to your response. 

- Hans Christian

**Comment by hanschr37** [comment]
Hi again, 
@bagedevimo @Bukashk0zzz @tflash @myh-denis 

Have you had the chance to look into my request from three weeks ago? 

Best, 

Hans Christian

**Comment by Bukashk0zzz** [comment]
Hi,

Issue fixed.
