### ISSUE TITLE
No se encuentra la plantilla en la galería de GTM

### ISSUE THREAD

**Issue by MonserratPG** [stape-io/klaviyo-tag#2]
Hola, al ingresar a mi cuenta de GTM a plantillas y buscar la de Klaviyo no aparece, me pueden ayudar para poder importarla o como buscarla.
Gracias
![image](https://user-images.githubusercontent.com/80537328/150178904-b15af19e-1b7e-49b0-9e0f-6333d4383536.png)

**Comment by Bukashk0zzz** [comment]
The tag is in the Community Template Gallery https://tagmanager.google.com/gallery/#/owners/stape-io/templates/klaviyo-tag
You try to add our tag to WEB GTM and not to the Server GTM container. 
And that's why you can't find it.
