### ISSUE TITLE
i can't save the tag

### ISSUE THREAD

**Issue by alimohamedyt55** [stape-io/klaviyo-tag#21]
There is a problem with Your Own Klaviyo custom tag when setup information and adding trigger, I can't save the tag. please help me
![Screenshot 2024-09-26 173307](https://github.com/user-attachments/assets/0cd3dae0-15b1-4d07-8c19-bdc18db522c8)

**Comment by alexbub** [comment]
To save you need to specify at least the Privat API Key and Event Name.

**Comment by alimohamedyt55** [comment]
I Can't save also, any solution

**Comment by alexbub** [comment]
Are you using the tag on a server-side GTM container?
Do you use the chrome browser to work with GTM?
This is definitely not a tag problem

**Comment by alimohamedyt55** [comment]
no im not using tag on server-side Container
yes I'm using chrome browser
