### ISSUE TITLE
Valor no válido en la vista previa de plantilla

### ISSUE THREAD

**Issue by jrodriguezf2024** [stape-io/klaviyo-tag#24]
I have this problem when I'm trying to import the template.

"Valor no válido en la vista previa de plantilla"

Image attach

![Screenshot_45](https://github.com/user-attachments/assets/46d1d5ac-4a97-4869-ba90-b0dd72767862)

**Comment by gvidoou** [comment]
This error occurs when you press "Run code", this is used for debugging templates. Just add template and then you can create tag with it. Here is the official guide https://support.google.com/tagmanager/answer/9454109?hl=en&ref_topic=3002579

**Comment by Bukashk0zzz** [comment]
@jrodriguezf2024 are you sure you use Server Side Google tag manager and not Web Google tag manager?

**Comment by jrodriguezf2024** [comment]
I am using Web Google Tag Manager. Could this be the reason why it's not working?

**Comment by Bukashk0zzz** [comment]
Yes, this tag for Server GTM
