### ISSUE TITLE
Forward all event data

### ISSUE THREAD

**Issue by bagedevimo** [stape-io/klaviyo-tag#3]
We're in a situation where it'd be very nice for us to forward all non-GTM event data fields though to GTM. I've forked your repo and gotten code to work nicely in this situation, mostly by trial and error figuring out the fields to exclude by default (for example x-gtm-version). Is this something you might accept a PR for, provided it's controlled via a toggle. I've also added the ability for users to specify fields to ignore, making it easy to skip fields that might have an impact on PII.

**Comment by Bukashk0zzz** [comment]
Yes, we are always open to new PRs.

Can you provide more examples of features you implemented?
How I see this that's it would be cool to add a feature similar to the official FB tag:
x-kl-param-name will be send to klavio as param-name.
What do you think?

**Comment by bagedevimo** [comment]
Yeah I mean that'd be cool and something i'm definitely opening to implementing. In our use-case, we literally want all params passed through to both our GA setup and our Klaviyo setup, so we just the the option to say "create an event in klaviyo with all the params present here excluding these ones". I have code something like this in my experiement:
```
const eventPropertiesToIgnore = ["x-ga-protocol_version", "x-ga-measurement_id", "x-ga-gtm_version", "x-ga-page_id", "x-ga-system_properties", "client_id", "language", "x-ga-request_count", "ga_session_id", "ga_session_number", "x-ga-mp2-seg", "page_location", "page_referrer", "page_title", "ip_override", "user_agent", "x-ga-js_client_id", "screen_resolution", "x-ga-mp2-user_properties"];
```

```
function sendEvent() {
  let excludeKeys = [];
  if(data.excludeProperties) excludeKeys = data.excludeProperties.map((n) => n.name);
  
  for(let key in allEventData) {
    const shouldIgnore = hasItem(eventPropertiesToIgnore, key);
    const shouldExclude = hasItem(excludeKeys, key);
    if(!shouldIgnore && !shouldExclude) {
      klaviyoEventData.properties[key] = allEventData[key];
    }
  }
  ```

**Comment by Bukashk0zzz** [comment]
Soon this update will be available in the GTM gallery.
