### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by Oztralia** [stape-io/klaviyo-tag#5]
Hi,
I don't see "Klaviyo" in the tag gallery anymore if I search for it. Additionally, i tried to follow the steps and import the template.tpl file as tag template, but it gives an error while importing. Doesn't say whats wrong...

can you provide an container import file?

**Comment by Bukashk0zzz** [comment]
Look like you trying add tag to WEB and not to Server container.
Tag is in Gallery.

<img width="582" alt="Screenshot 2023-06-02 at 11 17 17" src="https://github.com/stape-io/klaviyo-tag/assets/1908342/9278aefc-7fb9-4ec3-8759-1139e90e4df8">
