### ISSUE TITLE
Support for new API endpoints

### ISSUE THREAD

**Issue by vegajdr** [stape-io/klaviyo-tag#6]
With the Klaviyo API legacy endpoints scheduled for an [end of life for Jan 1, 2024](https://developers.klaviyo.com/en/docs/api_versioning_and_deprecation_policy), I was wondering if there are any current plans to update this template to support the new Klaviyo endpoints.

**Comment by Bukashk0zzz** [comment]
We have a plan to update this tag to the new API. 
We are Klaviyo users and use this tag ourselves. 

When we update this tag to the new API, I will inform you.

**Comment by Bukashk0zzz** [comment]
You can download template with new API https://github.com/stape-io/klaviyo-tag/blob/develop/template.tpl

**Comment by Bukashk0zzz** [comment]
Currently we do internal testing. And then will push changes to store.
Klaviyo changed API a lot. And not all will be working as before.
